HOSTS:
  debian-8-64:
    roles:
      - master
    platform: debian-8-amd64
    hypervisor: docker
    image: debian:8
    docker_preserve_image: true
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d'  # remove weird script file preventing openntpd from starting up
      - 'apt-get update'
      - 'apt-get -qqy install wget'

CONFIG:
  type: foss
  log_level: info
  trace_limit: 100
